### ISSUE TITLE
Switch node to use an archive rather than git

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.visualstudio.code.oss#1]
The git source for node makes building *really* slow since it's checking out a massive repo pretty slowly. If we switch to an archive source it should be considerably faster without any difference in the end product.

**Comment by amtlib-dot-dll** [comment]
OK, I'll change soon. My network is rather slow so it takes me time to calculate the checksums. Thank you for your advice

**Comment by amtlib-dot-dll** [comment]
@nedrichards Is there any change to the base runtime? The build starts to fail due to the missing `libgcrypt` library
* https://flathub.org/builds/#builders/5/builds/42
* https://flathub.org/builds/#builders/5/builds/38
