### ISSUE TITLE
Make ssh agent socket usable in the sandbox

### ISSUE THREAD

**Issue by mzabaluev** [flathub/com.visualstudio.code.oss#10]
The Visual Studio Code application can use git provided by the runtime, but it does not work with the ssh authentication agent provided by the desktop user session. It would be nice if `$SSH_AUTH_SOCK` from the host was made available in the sandbox and the environment variable imported. It seems easy to do with bwrap accordingly to flatpak/flatpak#1438.

**Comment by amtlib-dot-dll** [comment]
> It seems easy to do with bwrap accordingly to flatpak/flatpak#1438.

So I am afraid I am not able to help this, as an application maintainer but not a platform maintainer

**Comment by gasinvein** [comment]
@amtlib-dot-dll  A `--socket=ssh-auth` permission is implemented now, you can just add it to `finish-args`.
