### ISSUE TITLE
PlantUML extension doesn't see java, even though it's installed

### ISSUE THREAD

**Issue by tomsotte** [flathub/com.visualstudio.code.oss#14]
I've installed PlantUML extension, and it requires the `java` binary to be in PATH. I've installed openjdk and double-checked that it is recognized correctly and I can use it from any terminal.
But the extension does not see it.
I know flatpak does some kind of sandboxing, so my first guess is that it can't see any binary installed on the host machine. I've had the same problem with another extension that required `php` binary, which was installed on my machine but VS Code couldn't see it.

What can I do to let VS Code see some or all the binary that are required by some extensions?

I've tried to install from flathub `org.freedesktop.Sdk.Extension.openjdk9` but with no luck. Maybe the paths have to be exposed on building the app.

**Comment by TingPing** [comment]
Host libraries don't matter as its in a sandbox. The openjdk9 extension could work but you have to manually add it to PATH (in the sandbox). It is in `/usr/lib/sdk/openjdk9` or such.

**Comment by tomsotte** [comment]
How could I add the extension to the PATH in the sandbox?

**Comment by amtlib-dot-dll** [comment]
@tomsotte 
```sh
flatpak override --user --env=PATH=/usr/lib/sdk/openjdk9/bin:/app/bin:/usr/bin com.visualstudio.code.oss
```

**Comment by tomsotte** [comment]
Thanks a lot.
I hope this may help others who haven't found a way to add a lib or runtime to the PATH on a flatpak app.

**Comment by amtlib-dot-dll** [comment]
This should be a common problem for users who want to run development tools inside `flatpak`, as everything under `/usr` in the host system will be inaccessible
