### ISSUE TITLE
Difference between VS Codium and Code.OSS

### ISSUE THREAD

**Issue by paulcarroty** [flathub/com.visualstudio.code.oss#16]
@amtlib-dot-dll , [this project](https://github.com/VSCodium/vscodium) use simple <100 lines scripts. Maybe it will be interested to integrate their code here?

**Comment by amtlib-dot-dll** [comment]
Building Visual Studio Code is not a difficult job; the challenge is to build it without any Internet connection, and that is why `com.visualstudio.code.oss.json` is such a huge file. "Code - OSS" is just the name used in the upstream repo https://github.com/Microsoft/vscode/blob/master/product.json#L2 and I used it as is. "Code - OSS" only runs on the Flatpak platform but VSCodium seems to be able to run under Windows and/or macOS, however out of the sandbox. Nevertheless, thank you for your advice!
