### ISSUE TITLE
Access golang go binary

### ISSUE THREAD

**Issue by WobblingAgility** [flathub/com.visualstudio.code.oss#21]
When using Visual Studio for Go it would complain about the binary being missing. I found that the flatpak had access to the go binary at `/run/host/usr/bin`. Is it possible to update the flatpak PATH to include `/run/host/usr/bin`?

**Comment by WobblingAgility** [comment]
It seems that adding `/run/host/usr/bin` to the path did not work since on Fedora Silverblue is is linked to `/etc/alternative`, which the flatpak can not access. I found there was also a go binary in `/run/host/usr/lib/golang/bin` and I am using that with `flatpak run --env=PATH=/app/bin:/usr/bin:/run/host/usr/lib/golang/bin:$GOBIN com.visualstudio.code.oss`.

I was able to get VS working with Go this way but it doesn't seem practical. Would there be a better way to solve this issue?

**Comment by amtlib-dot-dll** [comment]
Install by `flatpak install flathub org.freedesktop.Sdk.Extension.golang`, and it will be under `/usr/lib/sdk/golang/bin/go`

**Comment by rodrigoaraujoti** [comment]
WobblingAgility it works. But I need to open the vscode only with this script. How can I define these as defaut params?

**Comment by amtlib-dot-dll** [comment]
`flatpak override` is your friend
