### ISSUE TITLE
Installing php in the sandbox or making host php command accessible

### ISSUE THREAD

**Issue by david-gr** [flathub/com.visualstudio.code.oss#22]
Hello,

I have installed some extensions that need php to work (PHP IntelliSense and Code Runner) but is not available in the sandbox.

I have seen #14 and #21 threads but i have found no solution to my problem.

I tried to document-export my host php file and i can read it from the vscode terminal, but i can't run it and i can't change permissions of the file to add the execute permission (`php.validate.executablePath` and `php.executablePath` are set). I get `Error spawning PHP: spawn EACCES`

Is there any way to install php inside the vscode sandbox from the terminal (or any other way)?
Is there any way of making the host php command accessible within the app?
Any other way of making this work?

Thank you.

OS: Linux Mint 19

**Comment by amtlib-dot-dll** [comment]
Alright, therefore you can run `LD_LIBRARY_PATH=/run/host/usr/lib:/run/host/usr/lib64 /run/host/usr/bin/php7.2` to indicate the path of the shared libraries needed by PHP.

**Comment by david-gr** [comment]
Thank you for your help @amtlib-dot-dll 

I'm not sure i'm doing this right.

If i run (same with sudo):
```
flatpak override --user --env=LD_LIBRARY_PATH=/run/host/usr/lib:/run/host/usr/lib64 /run/host/usr/bin/php7.2
error: '/run/host/usr/bin/php7.2' no es un nombre de aplicación valido: Name can't start with /
```
I have tried with this:
```
sudo flatpak override --user --env=LD_LIBRARY_PATH=/run/host/usr/lib:/run/host/usr/lib64:/run/host/usr/bin
```
but i still get the same:
```
sh-4.3$ echo $LD_LIBRARY_PATH
/run/host/usr/lib:/run/host/usr/lib64:/run/host/usr/bin
sh-4.3$ php -v
sh: php: command not found
sh-4.3$ php7.2 -v
sh: php7.2: command not found
sh-4.3$ /run/host/usr/bin/php -v
sh: /run/host/usr/bin/php: No such file or directory
sh-4.3$ /run/host/usr/bin/php7.2 -v
/run/host/usr/bin/php7.2: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory
```

Anyway i have checked it and there is no lib64 (same result in host)
```
sh-4.3$ ls /run/host/usr/
bin  games  include  lib  local  sbin  share  src
sh-4.3$
```

**Comment by amtlib-dot-dll** [comment]
Okay, may I ask you where is the required library file in your host system? That is, may you paste the output of these two commands here?

* `ldd /run/host/usr/bin/php7.2` (run this command inside the sandbox)
* `ldd /usr/bin/php7.2` (run this command outside the sandbox)

**Comment by amtlib-dot-dll** [comment]
Alright, `export LD_LIBRARY_PATH=/run/host/usr/lib/x86_64-linux-gnu; /run/host/usr/bin/php7.2 --version` would help, or fail with a different error 👀

**Comment by david-gr** [comment]
```
sh-4.3$ export LD_LIBRARY_PATH=/run/host/usr/lib/x86_64-linux-gnu; /run/host/usr/bin/php7.2 --version
/run/host/usr/bin/php7.2: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
```
:confused:

**Comment by amtlib-dot-dll** [comment]
@G-Ray You may try running `/var/lib/flatpak/apps/com.visualstudio.code.oss/current/active/files/share/code-oss/code-oss` directly. 🤔

**Comment by G-Ray** [comment]
Yeah nice solution I guess ahah. I like to use the terminal to run my npm scripts, so I would need to have access to my nodejs install

**Comment by amtlib-dot-dll** [comment]
@G-Ray 
> Yeah nice solution I guess ahah. I like to use the terminal to run my npm scripts, so I would need to have access to my nodejs install

If your installation is located under `/home`, it can be easily accessed; if it is located under `/usr` or `/opt`, you can find it under `/run/host` inside the sandbox. The only exception is that some executables depend on shared libraries which are located under `/lib` on distributions in which `/lib` is not a symbolic link to `/usr/lib`, and thus inaccessible as in this issue.

**Comment by EvanWashkow** [comment]
@G-Ray @amtlib-dot-dll 

I fought this forever, until I read this little line on http://docs.flatpak.org/en/latest/sandbox-permissions.html:

> * These directories are blacklisted: /lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var
> * These directories are mounted under /var/run/host: /etc, /usr

I tried this in VirtualBox (host is Manjaro), and it worked for me! Here are the steps I did, below:
1. Installed PHP via `sudo dnf install php`
2. Installed Visual Studio Code via FlatHub (doesn't matter if it's OSS or not)
3. Search for setting "PHP > Validate: Executable Path"
4. Use the link to edit the User Settings JSON file
5. Set `"php.validate.executablePath": "/var/run/host/usr/bin/php"`

Note: *You do not have to use any Flatpak commands to edit any options of Code. It just works!!*

**Comment by tomsotte** [comment]
@EvanWashkow

I'm on Fedora too, Workstation 29 x64, but I couldn't make it work as easy as you said. I've installed PHP via dnf, but when I try to run PHP via terminal it goes as the previous post, it cannot access shared libs:

```
sh-4.3$ /var/run/host/usr/bin/php
/var/run/host/usr/bin/php: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory
```

**Comment by TingPing** [comment]
This issue has gone completely off the rails. You can't run host things in the sandbox that is nonsensical.

There is one and only one way to run a host tool in the sandbox:

`flatpak override --user --talk-name=org.freedesktop.Flatpak com.visualstudio.code.oss`

Then in the sandbox `flatpak-spawn --host php` (or any tool).

**Comment by tomsotte** [comment]
Thanks a lot, it seems to work now.

As a follow up to your answer, I had to add a file with the `flatpak-spawn` command to use it as an executable path, as required by some extensions.

For example I made the file `flatpak-php` in `/home/user/bin` and gave it execution permission via `chmod +x`.

```sh
#!/usr/bin/env sh
flatpak-spawn --host php "$@"
```

And then added the path in the JSON Settings of VS Code like this:

```json
"php.validate.executablePath": "/home/user/bin/flatpak-php"
```

**Comment by stobbsm** [comment]
I have a pull request open to add php 7.3 as an SDK item like dotnet. You can always pull that and build it for your use until it's accepted (not sure what the holdup is, tbh).
