### ISSUE TITLE
Consider upgrading to org.freedesktop.Platform/x86_64/18.08

### ISSUE THREAD

**Issue by Iolaum** [flathub/com.visualstudio.code.oss#23]
Thank you to the developers for this app.

If possible consider upgrading to org.freedesktop.Platform/x86_64/18.08.

**Comment by amtlib-dot-dll** [comment]
Ongoing. Actually the base runtime has been switched back to 1.6 because of the lack of some executable as explained in #12

**Comment by Wetrain** [comment]
did you open an issue at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/ @amtlib-dot-dll ?

**Comment by amtlib-dot-dll** [comment]
Already upgraded
