### ISSUE TITLE
Visual Studio Code - OSS crashes when opening anything really

### ISSUE THREAD

**Issue by omrllm** [flathub/com.visualstudio.code.oss#27]
When I try to open a file or I try to open in general a folder/file/workspace, the app crashes.

I've tried to uninstall it from the software package manager and reinstall it from the terminal with `flatpak install flathub com.visualstudio.code.oss`, but the error persists.

If I try to click New File, the app works correctly.

System running: Fedora 
Version: 29

Update: Same story with the proprietary version of VSCode provived via the flathub repo.
The snap VSCode proprietary version works instead.

**Comment by amtlib-dot-dll** [comment]
Is there any logs?

**Comment by amtlib-dot-dll** [comment]
Does not happen in my Fedora 29. Anybody else?

**Comment by omrllm** [comment]
> Is there any logs?

How can I see that?

**Comment by amtlib-dot-dll** [comment]
Probably not. I don't have such an issue in the same OS as you, so I don't know where to dig into it. It would be better if you provide more information.
