### ISSUE TITLE
Consider adding --allow=devel finish arg

### ISSUE THREAD

**Issue by ahayzen** [flathub/com.visualstudio.code.oss#29]
Comparing code.oss to code in flathub there are some differences in finish-args, the first I noticed is that the non-oss one has `--allow=devel` [0].

As per the flatpak docs [1] this has a few purposes "...the --devel option tells Flatpak to use the SDK as the runtime, which includes debugging tools like gdb. The --devel option also adjusts the sandbox setup to enable debugging.".

Furthermore "When the --devel option is used, Flatpak will automatically use any matching debug extensions that it finds." this sounds like `sdk-extensions` [2] can be dropped and will instead be automatically picked up - so the manifest then doesn't need to list all the extensions.

0 - https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.json#L20
1 - http://docs.flatpak.org/en/latest/debugging.html
2 - https://github.com/flathub/com.visualstudio.code.oss/blob/master/com.visualstudio.code.oss.json#L26

**Comment by ahayzen** [comment]
I have pushed a branch which shows the sort of changes proposed, https://github.com/flathub/com.visualstudio.code.oss/pull/30. This has not yet been tested, I have only tried the `--allow=devel` using local overrides which allows for gdb to run.

**Comment by ahayzen** [comment]
@amtlib-dot-dll 
1) No worries, it was just something I noticed when comparing the OSS and non-OSS versions.
2) Ah I see that is for the tools :-)

Sure maybe something in the README stating that `--allow=devel` can be used to allow for debugging could be useful. Feel free to close this issue and the pull  :-)

**Comment by amtlib-dot-dll** [comment]
Additionally, the recipe file is not written by myself. 😂 The JSON file is generated by the Python script `build.py` so don't modify the JSON file directly.
