### ISSUE TITLE
Not use org.freedesktop.Sdk as runtime?

### ISSUE THREAD

**Issue by peteruithoven** [flathub/com.visualstudio.code.oss#33]
For starters, thanks for making Visual Studio Code available trough flatpak!

So this is probably a silly question, but is there anyway visualstudio code can not use `org.freedesktop.Sdk` as it's runtime? 
I'm asking mainly because It's a whopping 4,6 GB and as a laymen regarding Flatpak it seems weird to use a sdk as a runtime.

**Comment by TingPing** [comment]
It uses the Sdk because its a developer tool and things like `clang`, `git`, `python2`, etc are valuable for developers.

**Comment by amtlib-dot-dll** [comment]
Yep, and even for non-devs `git` is very useful. Actually I changed the runtime to the `.Sdk` one when I tried to embed `git` into this application and then realized a better solution. BTW, additional dev tools like OpenJDK, Rust and Swift which are packed in `.Sdk.Extension.*` extensions can only be loaded when the `.Sdk` runtime is used.
