### ISSUE TITLE
Improve OSS description

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.visualstudio.code.oss#34]
Hey,
Normally not a copywrighter, but since the text got me confused a lot longer then I dare to admit, allow me to propose a new version of the description of the OSS version.

## Official version
> Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle.
> 
> This is the proprietary Microsoft build of Visual Studio Code, packaged into a Flatpak. This repackaging is not supported by Microsoft.

## Current OSS version

> Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle. See `https://code.visualstudio.com/docs/setup/linux` for installation instructions and FAQ.
> 
> The above paragraph, from upstream Microsoft, is the same for this OSS version and the non-OSS version `https://flathub.org/apps/details/com.visualstudio.code`. The difference between them is described at `https://github.com/flathub/com.visualstudio.code.oss/issues/6#issuecomment-380152999`. This version is compiled directly from the source code provided in the upstream GitHub repository with minor modifications, as the official binary is licensed proprietarily. Essential features are all present.

## Proposed OSS version
> Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle.
> 
> This is the Open Source build of Visual Studio Code, packaged into a Flatpak. Some features are different from the proprietary version: There is no telemetry, Twitter integration is missing, and it uses a different logo.  This repackaging is not supported by Microsoft.
> 
> For more information, see `https://github.com/flathub/com.visualstudio.code.oss/issues/6`

I hope that the new paragraph is easier to read and understand, so that users can make a better informed decision. It also removes the erroneous installation information. You're linking to a guide about how to add a Microsoft repository to your distro, which is of cause not applicable for a flatpak.

## Edit
Additional comment. The current `website`-button in the Software Center redirects to the Microsoft site. Perhaps better to redirect it to this github?

**Comment by amtlib-dot-dll** [comment]
Thanks, and I'd consider it. But unfortunately Travis CI is temporarily inaccessible in my region, so I have to wait for some time. The JSON recipe file is generated by that Python file in the repository automatically in Travis, and it's down while I cannot know why. Sorry for inconvenience

**Comment by amtlib-dot-dll** [comment]
Travis CI is on AWS and AWS is temporarily inaccessible from my ISP :man_shrugging:

**Comment by amtlib-dot-dll** [comment]
Changed 7eb378f441fe25b9f4e95db5e33744934078f9d3. Thanks!
