### ISSUE TITLE
New installation has Telemetry (presumably) on in settings menu

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.visualstudio.code.oss#35]
After installing the flatpak version and going through the settings menus, I discovered that Telemetry was on, without touching it. 

It might be for two reasons:
* The UI is not properly updated to reflect the missing Telemetry
* The process of compiling and including Telemetry has changed

Version info:
* 1.30.2 of Visual Studio Code - OSS 
* com.visualstudio.code.oss/x86_64/stable
* Ubuntu 18.10 64bit

![screenshot from 2019-02-11 15-26-17](https://user-images.githubusercontent.com/33983090/52569491-99baf900-2e11-11e9-9ae3-cff0368fd3f8.png)

**Comment by amtlib-dot-dll** [comment]
I don't know the very detail of it, but I suspect that the XML file controlling the setting items are identical to the proprietary one, while the JSON file configuring the real telemetry endpoint (`product.json`) is different in the OSS version, and therefore there is no actual telemetry. However, I am just guessing :nerd_face:

**Comment by Eonfge** [comment]
Could not reproduce
