### ISSUE TITLE
Python 2.7 not present in latest release

### ISSUE THREAD

**Issue by xdraylin** [flathub/com.visualstudio.code.oss#39]
Python 2.7 is not available in the latest release (probably removed with commit e1ece9895473e15fbfeae09988a57e46fd6f6a5f) which breaks Python2.7 linting and dependend plugins such as PlatformIO.

**Comment by amtlib-dot-dll** [comment]
@TingPing I noticed that Python 2.7.16 is still included in `org.freedesktop.Sdk//18.08`, though not in `org.freedesktop.Platform//18.08`. Will they be removed or kept in the future?

**Comment by amtlib-dot-dll** [comment]
@xdraylin A temporary solution is to run `flatpak install flathub org.freedesktop.Sdk//18.08` and then `flatpak run --runtime=org.freedesktop.Sdk//18.08 com.visualstudio.code.oss`

**Comment by smnscp** [comment]
Thanks @amtlib-dot-dll, that helped me, too, though for me it was **git** that was suddenly missing.

**Comment by TingPing** [comment]
Use the Sdk for this package, no idea why you would stop, especially now that the Sdk is about to dramatically shrink in size.

**Comment by ricvelozo** [comment]
Git is missing for me, and [rust-lang/rls-vscode](https://github.com/rust-lang/rls-vscode) is not finding Rust, which usually is installed in home directory.

**Comment by amtlib-dot-dll** [comment]
I have pushed the latest version 3 days ago but it is still in the publishing process flathub/flathub#962

**Comment by smnscp** [comment]
Version 1.33.0 is available on Flathub now. Thanks for the fix, @amtlib-dot-dll!
