### ISSUE TITLE
[Upstream org.freedesktop.Sdk//18.08] Python 2.7 sitecustomize not working

### ISSUE THREAD

**Issue by xdraylin** [flathub/com.visualstudio.code.oss#40]
I'm opening this issue just to help others currently having a problem installing PlatformIO or some other plugins relying on Python2.7 and running into other issues with Python.

The latest upstream update of org.freedesktop.Sdk//18.08 (50d66eb87b1fd6db736912ec285b99848f81d1854c1bce3f5af837f786baf138) breaks the sitecustomize module and therefore prevents the installation of at least PlatformIO. When running `python2.7` directly on command line the error `import sitecustomize' failed; use -v for traceback` is shown.

To downgrade back to the previous version of the Sdk and fix this problem, execute:
`flatpak update --commit=883db2614bbaf1b231d90d5ed1ea1cd01d5eda9af5005e485eeb30a16e38d19f org.freedesktop.Sdk//18.08`

**Comment by amtlib-dot-dll** [comment]
Perhaps you need to submit an issue at the upstream repo https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues

**Comment by nanonyme** [comment]
This should work with release .32 at least.
