### ISSUE TITLE
Idea: Rename app title/name to “VSCodium”?

### ISSUE THREAD

**Issue by alexander255** [flathub/com.visualstudio.code.oss#42]
This is just an idea, but another application VSCode fork named VSCodium has popped up with pretty much the same goals as this package that I've happily been using for quite some time. They even [mention you in their download section](https://vscodium.com/#flatpak) as “[…] open source build of Visual Studio Code without telemetry, very similarly to VSCodium.”.
Unlike the current Flatpak package title/menu item name, I think their name clearly indicates that they are somehow different but still related to the official VSCode builds published by MS.

What do you think about this? I'll also open an issue with them, to ask them about their opinion on this.

**Comment by alexander255** [comment]
Other issue: https://github.com/VSCodium/vscodium/issues/199

**Comment by amtlib-dot-dll** [comment]
Naming things is difficult and I am lazy. Sorry, no

**Comment by nedrichards** [comment]
As mentioned on the other ticket - that app has a specific configuration and branding. This could only use that if the specific configuration was adopted.
