### ISSUE TITLE
Desktop entries are broken for version 1.39.1

### ISSUE THREAD

**Issue by articlecat** [flathub/com.visualstudio.code.oss#48]
The desktop entries are broken in version 1.39.1. Here is the relevant part of `/var/lib/flatpak/exports/share/applications/com.visualstudio.code.oss.desktop`:

```
[Desktop Entry]
...
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=@@EXEC@@ --file-forwarding com.visualstudio.code.oss --unity-launch @@ %F @@
...
[Desktop Action new-empty-window]
...
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=@@EXEC@@ --file-forwarding com.visualstudio.code.oss --new-window @@ %F @@
Icon=com.visualstudio.code.oss
```

The `@@EXEC@@` should be replaced with the application path. Changing [line 844 of build.py](https://github.com/flathub/com.visualstudio.code.oss/blob/886943ee01a3080a296af69f246f949b3736e6a2/build.py#L844) to
```
        .replace('@@EXEC@@', '/app/share/' + product['applicationName'])
```
would probably resolve this.

Until this is fixed, users can still run vscode through `flatpak run com.visualstudio.code.oss` in the shell.

Users can also override the broken desktop entry by copying `/var/lib/flatpak/exports/share/applications/com.visualstudio.code.oss.desktop` to `~/.local/share/applications/com.visualstudio.code.oss.desktop` and replacing the affected lines with:
```
[Desktop Entry]
...
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/share/code-oss/code-oss --file-forwarding com.visualstudio.code.oss --unity-launch @@ %F @@
...
[Desktop Action new-empty-window]
...
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/share/code-oss/code-oss --file-forwarding com.visualstudio.code.oss --new-window @@ %F @@
Icon=com.visualstudio.code.oss
```

Related: https://bugs.archlinux.org/task/64129

**Comment by amtlib-dot-dll** [comment]
Good! Thank you very much for your advice, and I'll change it soon!
