### ISSUE TITLE
Indicate difference to non oss version in description

### ISSUE THREAD

**Issue by FlorianLudwig** [flathub/com.visualstudio.code.oss#7]
The packages `com.visualstudio.code.oss` and `com.visualstudio.code` have the exact same description, please include a note explaining the difference of the two packages.

**Comment by TingPing** [comment]
Difference was described here: https://github.com/flathub/com.visualstudio.code.oss/issues/6

If somebody wants to add that to the description.

**Comment by amtlib-dot-dll** [comment]
I'll add when I have time. Or you can submit a PR @FlorianLudwig 🤣

**Comment by nedrichards** [comment]
I've added a small explanation to the proprietary version. I'd prefer to try and keep this as close to unmodified upstream as possible.

**Comment by FlorianLudwig** [comment]
@nedrichards thanks!
